---
title: "🧩IT English Experssions 004"
description: Daily English Series
date: "2022-10-24"
categories: [daily, english, it, note]
toc: true
---

> 영어 회화 표현이나 논문에서 쓸 수 있는 유용한 표현들을 조금씩 익히기 위해 시작한 1000일 시리즈 포스트 입니다. 공부 리소스는 유튜브, 리얼클래스, [PN님의 블로그](https://in.naver.com/sw4r), cake 어플, 책, 논문, 기사 등 다양한 출처에서 보고 기록합니다.

## Git으로 세련되게 협업하는 방법

### Conventional Commits

- 커밋 메세지는 `Subject (Title)`, `Body`, `Footer`로 구분
- 구조

```
<type>[optional scope]:<description>
[optional body]
[optional footer(s)]
```

- 예시([http://www.conventionalcommits.org/](http://www.conventionalcommits.org/))

```
fix: prevent racing of requests                           ---> Subject or Title
Introduce a request id and a reference to latest request. ---> Body
Reviewed-by : Z                                           ---> Footer(s)
Refs : #123
```


### Subject(Title) 작성법

커밋 메세지의 제목은 변경사항을 **대표**하는 텍스트이므로 대표적인 타입들이 있다.

- **feat**: 코드에 새로운 기능(=feature) 추가
- **fix**: 버그 수정
- **BREAKING CHANGE**: 이전 버전과 호환되지 않는 변경 내역. `!`으로 표시할 수 있음. e.g.) `feat!:`
- **docs**: 개발 문서 변경
- **style**: 들여쓰기, 따옴표, 세미콜론 등 코드 형식 및 스타일 변경
- **ci**: CI/CD(continueout integration and deployment) 관련 코드 변경
- **refactor**: 중복된 코드 제거, 변수명 변경, 코드 단순화 등 리팩터링
- **test**: 테스트 관련 코드 변경
- **build**: 빌드 시스템 관련 코드 변경
- **perf**: 성능 개선 관련 코드 변경
- **chore**: 기타 코드 변경

예시

- `fix: remove deprecated features` 수정: 권장되지 않는 기능 삭제
- `feat: add parameters to getImage` 기능: getImage에 매개변수 추가
- `docs(readme): update build instructions` 문서(readme): 빌드 지침 업데이트
- `chore: update np dependencies to latest version` 기타: npm 의존성 최신버전으로 업테이트

나만의 예시 연습

- `docs(readme): add new papers "THE TITLE OF PAPER"`
- `feat: add getJointPosition function`
- `refactor: delete overlapped constants and variables of robot model`

### 5가지 커밋 작성법

1. 동사 원형으로 시작
- **제목**은 명령적 어조(Imperative Mood)의 동사원형으로 시작
- **Body, Footer**는 명령문이 아니어도 됨
- 상황에 따라 과거형(e.g. `Added`) 또는 3인칭 단수 현재형(e.g. `Adds`)를 사용하기도 함
- 커밋 메세지에 **자주 등장하는 동사**
    - `Fix`: 수정하다
    - `Improve`: 개선하다
    - `Handle`: 처리하다
    - `Optimize`: 최적화하다
    - `Update`: 업데이트하다
    - `Implement`: 구현하다, 적용하다
    - `Refactor`: 리펙터링하다
    - `Add`: 추가하다
    - `Revert`: 되돌리다
    - `Change`: 변경하다
    - `Replace`: 대체하다
    - `Merge`: 병합하다
    - `Document`: 문서를 작성하다
    - `Bump`: 버전을 올리다
    - `Simplify`: 단순화시키다
    - `Enable`: 가능하게 하다
    - `Run`: 실행하다
    - `Clean`: 제거하다, 정리하다
    - `Wrap`: 감싸다, 그룹화하다
    - `Deploy`: 배포하다
    - `Modify`: 변경하다
    - `Remove`: 제거하다
    - `Rename`: 이름을 바꾸다
    - `Move`: 이동하다, 이동시키다


2. 모두 소문자로 또는 첫 글자만 대문자로

- Conventional Commits 형식에서는 모든 문자를 **소문자**로 작성. `type: description`에 맞추어 메세지 작성
- Conventional Commits 형식을 적용하지 않는 경우, 일반적으로 앞부분만 대문자 사용하고 type 생략
- 예시

```
[1] docs: update build.md with detailed instructions
[2] Update build.md with detailed instructions
```

3. 관사(a, an, the와 같은 Article) 생략

- 커밋 타이틀은 최대 50글자 제한
- 핵심 키워드만 활용하여 메세지를 작성하기 위해 관사 생략
- 예시

```
[X] Fix a typo in the header
[O] Fix typo in header
```

4. 마침표와 같은 구두점(Punctuation Mark) 생략

- 반드시 필요한 경우가 아니면 쉼표, 하이픈 등 생략
- 예시

```
[X] feat: implement google analytics.
[O] feat: implement google analytics
```

5. 변경한 이유, 상세한 설명은 본문(Body)에

- 코드 변경 사유와 상세 설명은 커밋 본문에 씀

### Git 주요 실무 영어

- `Squash the last 3 commits`: 최근 3개 커밋을 합치다
- `Push commits to a repository`: 리포지터리(코드 저장소)로 커밋을 전달하다
- `Merge a feature branch into the base branch`: 기능 브랜치를 기본 브랜치에 병합하다
- `Revert a pull request`: 풀 리퀘스트를 되돌리다(이전 상태로 되돌리다)
- `Request a review`: 검토를 요청하다
- `Comment on a pull request`: 풀 리퀘스트에 댓글을 남기다
- `Resolve a merge conflict`: 병합 충돌을 해결하다
- `Rebase onto another branch`: 다른 브랜치로 리베이스(base를 재설정하여 커밋 재적용)하다
- `Clone a repository`: 리포지터리를 복제하다
- `Close a pull request without merging it onto the branch`: 풀 리퀘스트를 병합하지 않고 종료하다
