---
title: "📘Goodbye 2024"
description: 체감상 3배 압축된 시간을 보냈던 2024 회고
date: "2025-01-05"
categories: [diary, 2025]
toc: true
execute:
  freeze: auto 
---

2024 정말 잊지 못할 한해였습니다.

사람이 살아가면서 많은 마일스톤들이 있고, 그 마일스톤을 한해에 하나 담기도 어려운 법인데 2024는 3가지 마일스톤들이 지나간 해였기에 가장 기억에 남지 않을까 싶습니다.

1. 석사 졸업
2. 취업 준비
3. 이직

하나 하나의 키워드가 굵직굵직해서 솔직히 지금도 이게 저한테 한해동안 일어난 일이었던가 어떨떨하긴 한데, 돌이켜 보면 정말 그렇습니다. 그렇기에 2024년도 회고야 말로 정말 쓸것도 많고 다시 되짚어 볼 것도 많은 것 같습니다. 가장 기억이 나지 않는 1월부터 달력을 짚어보며 회고를 시작해보겠습니다.

---

## 1월 

12월 폭풍 전야와 같은 논문 심사를 마치고 마지막 논문 편집을 하며 시간들을 보내고 있었습니다. 2년 동안 다사다난했지만 결국 이 논문 한편을 위해 달려왔다는 사실을 다시 깨닫게 되는 시간이었고, 내 자신이 나름 대견하다고 생각하며 마지막 졸업 논문 편집을 달리고 있었습니다. 비록 졸업 논문이기에 많은 사람들이 읽고 피드백을 주는 연구적인 임팩트가 큰 결과물이라고 볼 수는 없지만, 석사 기간동안 내가 공부한 것들과 주장하고자 하는 것들을 정리하는 시간이 지금까지도 큰 거름이 되는 것 같습니다. 

졸업을 하고 한동안은 나에게 주는 휴식 선물로 취직을 바로 할 생각이 없없지만, 말할 수 없는 사정에 의해 바로 취준을 시작했습니다. 그래서 아직 공채 기간이 시작되지 않았기에 스타트업들 위주로 열심히 지원서들도 쓰기 시작했던 기간이었습니다. 물론 석사 연구 내용과 유관한 직무들을 찾긴했었지만 막상 사회생활 전선으로 나아가니 나를 어필할 부분이 많지 않아 당황스럽기도 하고 조금은 좌절스럽기도 했지만, 다른 측면으로 나의 성과들을 돌아보고 정리할 수 있어서 좋았던 것 같습니다. 취준을 하면서 가장 막막했던 점은 코딩 테스트와 같은 스킬적인 측면을 보는 것들이 스트레스가 심했었는데, 아무래도 지금까지 연구 코드만 작성해오던 사람이라 알고리즘 능력에서는 많이 부족하기도 하고 시간 제한이 있는 상황이 익숙하지 않았던 것 같습니다. 

## 2월

2월은 졸업식이 있었습니다. 대학교 졸업때는 코로나 시기였기에 친구들도 초대하지 못하고 바로 입학할 대학원으로 복귀해야 하는 상황이어서 졸업식을 잘 즐기지 못했던 아쉬움이 있었습니다. 하지만 석사 졸업은 연구실에 단 한명 졸업에다가 친구들도 초대해서 *진정한* 주인공 놀이를 할 수 있었던 것 같습니다.



## 3월

## 4월

## 5월

## 6월

## 7월

## 8월

## 9월

## 10월

## 11월

## 12월

## 마무리

한때 회고를 남기는 것에 대해 회의적일 때가 있었습니다. 