---
title: "📘찌질의 역사, 그 서막"
description: 찌질했던 나 그대로
date: "2023-03-27"
categories: [diary, jjijil, 2023]
toc: true
execute:
  freeze: auto 
---

찌질했던 나 그대로
감당 가능하시겠습니까?

숨기고 싶은 다이어리 시리즈로 `찌질`이라 명칭을 정해봤습니다. 뭔가.. 영문으로 `jjijil`로 로마자 표기가 마음에 들어서 그런 것도 있습니다.

### 서문 같지 않은 서문 

벌써 돌고 돌아 석사 2년 차가 됐습니다. 푸릇했던 3월도 이제 막바지고요.

작년 이맘때에 엄청난 포부가 있었습니다. 매일 일기를 써가면서 힘든 시간 지혜롭게 이겨낼 그 결심.

그런데 지금까지 힘든 일들이 있을 때마다 머리로, 가슴으로 삼키면서 쓰질 않았어요. 사실 기쁜 일들도 기록하면 그 때의 나를 돌아보며 `인생 헛 살진 않았구나` 위로도 받을 심산이었는데.

양면적인 감정이었습니다. 누군가에게 회포로 풀고 싶으면서도 감추고도 싶고. 주변 사람들이 알아주길 바라면서도 알까봐 두려웠거든요.

아마 나 스스로에게도 꺼내보고 싶은 마음과 함께 꺼내면 무너질 것 같은 두려움에 굳이 펜을 들거나 메모장을 키지 않았던 것 같습니다.

이전에 한 헛소리들이 그렇게 영향을 주지도 않을텐데 말이죠.

### 나를 대하는 태도

누군가는 제가 스스로에게 너무 높은 허들을 대고 있다고 합니다.

그럴수도 있겠지만 그 허들을 굳이 내릴 마음이 없습니다. 아니, 정확히는 내리는 법을 몰라서 일수도 있겠지만요.

허들을 낮추는 게 두렵습니다. 저는 참 두려운 게 많은 사람이네요. 

### 나에 대한 생각

예전부터 저는 제가 특별하다고 생각했습니다. 모두가 그렇겠지만 세상은 각자의 중심대로 흘러가니까요. 마치 전생이 있다면 고귀한 어떤 왕가의 책임자(왕 혹은 왕비)였을 거라고 생각했었죠. 그래서 누가 알아주지 않더라도 스스로 생각하기에 부끄러운 일은 안하려고 하고, 어려운 길이 있다면 마치 숭고한 희생을 치른다는 듯이 나서서 행동했던 기억이 있습니다. 천재라고도 생각했습니다. 괴짜 천재라기 보다 고상함에 고집을 섞은 연구자의 모습이랄까요. 그래서 제가 시대물 컨텐츠들을 좋아하나 봅니다.

살아가면 살아갈수록 난 우주먼지인게 안심이 됩니다. 생각보다 내가 뭘 한다고 해서 큰일이 나지는 않는 것 같더라구요. 예전엔 내가 한 행동들이 큰일을 만들어내야 한다고 생각했었는데 지금은 오히려 산속에서(혹은 자연 그 어딘가) 내 주변의 변화를 관찰하고 행복을 느끼는 정도로 살아가는 존재였으면 합니다.

### 요즘

지친 것일 수도 있고 현실을 자각한 것일 수도 있겠습니다만, 생각보다 이 상태를 즐기고 있다고도 생각합니다. 아까 허들을 낮추는게 두렵다고 했었던가요? 요즘 그 허들 낮추는 걸 잘 터득하고 있는 것 같기도 해요.

평생 돈 안벌고 걱정없이 뭐하고 싶냐고 질문을 받아본 적이 있습니다. 그때 그냥 `편집샵`이라는 단어가 생각났었는데요. 내가 좋아하는 거 내가 원하는 거 모아둔 그 어떠한 시공간의 요소를 말한 것 같습니다. 그 편집샵에 온 사람들이 물건을 사거나 후원을 하지 않더라도(영어 표현이 더 맞는 것 같아 덧붙이자면 judging 이라는 거겠죠.) 내가 나임을 온전히 받아들이고 집중할 수 있는 공간. 생각보다 제가 눈치를 많이 보거든요. 안보는 척 연기를 잘해서 그렇지.

### 마무리

두서 없이 적는 게 재밌네요. 제목도 하나도 내용과 안맞고. 사실 읽을 사람은 훗날 나밖에 없으니 막 적는 것 같네요. 찌질했던 나 그대로 감당합니다.
