---
title: "📘난 연구를 하러 왔습니다"
description: 배부른 소리일까요
date: "2023-03-30"
categories: [diary, jjijil, 2023]
toc: true
execute:
  freeze: auto 
---

매일 아침 일어나서 고민을 합니다. 

연구실을 가야 하나 말아야 하나. 가기 괴롭거나 힘드냐구요? 아뇨 근데 그것보다 더 큰 문제인 갈 필요성을 못 느낍니다.

가는 동안 약 2kg의 짐을 들고 2시간 정도는 길에서 시간을 보내야 하거든요. 근데 이게 문제는 아닙니다.
저는 짐 드는 건 아무렇지 않고 원래 대중교통에서 시간보내는 게 피곤하긴 해도 싫어하는 타입은 아니거든요.
그리고 사실 짐은 연구실에 자주 간다면 원래는 놓고 다니는 거였기 때문에 장애물도 아닙니다.

그런데 근본적으로 연구실에 갈 이유가 없습니다.

연구실에 다들 왜 가나요? 연구 환경이 있기 때문입니다.
연구환경..물질적인 자리 셋팅이나 기자재 등도 있겠지만 무엇보다 중요한 건 내 연구를 하면서 간단한 디스커션이라도 할 사람 만나러 가는 공간입니다.
그런데 나에겐 그런 공간이 아니라서 갈 이유를 모르겠습니다.

내가 이기적인 것 같다고 생각도 해봤습니다. 근데 이건 이기적인게 아니라 말이 되는 겁니다.

내가 뭘 하는지 모르는 교수님과 내 연구주제에 대해 관심이 없거나 모르는 동료들에게 매번 설득해야 하는 포지션도 지쳤습니다. 제가 모자른 거겠죠. 내가 자료가 충분히 없었고 내가 잘 모르고 내가 말 주변이 없고. 근데 왜 나한테만 문제를 느껴야 하는지 모르겠습니다. 나는 연구를 하러, 지도를 받으러 연구실에 왔습니다. 와서 내가 모자른 모습들만 보며 슬퍼하려고 돈주로 학교에 온 게 아닙니다. 내가 모자른 모습에서 성장할 동력을 얻을 만한 코멘트를 받는 게 아니라 그냥 의사소통이 안되는 느낌입니다. 처음에는 설명하고 설득하고 하면서 내 실력도 올라가고 이것또한 내 일일 것이다 생각하며 스스로를 다독였습니다. 그런데 결국 나는 혼자라는 걸 깨달았고 이제는 문을 닫고 살 궁리만을 하고 있습니다. 저도 압니다. 그럴 수록 나만 힘들어진다는 거. 그동안은 물리적인, 경제적인 뒷받침에 감사해하며 넘길 수 있는 문제였는데 이젠 불편한 생각과 감정이 덮어진다고 덮어지지도 않습니다.

일례로, 오히려 다른 과 사람들과 프로젝트를 진행하면서 대화가 되고 아이디어가 진척이 많이 됐는데 결국 교수님 눈치봐야하고 승낙을 받기 전까지는 마치 비밀첩보처럼 사이드 프로젝트처럼 진행하는 게 스트레스 받아서 제가 그만 두었습니다. 그런데 왠걸요. 최근에 그 아이디어로 논문이 나오더군요. 솔직히 속에서는 욕이 나왔습니다. 사람들 생각은 다 비슷하고 나도 그 흐름을 쫓아갈 수 있었는데 항상 놓치는 이 포지션이 짜증났습니다.

진짜 내가 잘못 랩을 선택한 거였구나. 인정했습니다.

그럼 이제 어떻게 해야할까요?

3월 내내 방황했습니다. 근데 답은 하나밖에 없습니다. 제가 결과를 만들어서 나가는 수 밖에요. 

근데 더 돌겠는건, 나는 평범한 소시민이라는 겁니다.